### PR TITLE
Add note about deadlock during create_hypertable

### PR DESCRIPTION
**Pull request by k-rus**
Adds warning of deadlocking during create_hypertable for tables with foreign key constraints.

### CODE REVIEW

**Comment by k-rus** [comment]
Cherry-picked #290

**Comment by solugebefola** [comment]
Is there additional info that's not in #290?  Otherwise it's going to get merged into `v1.6.1` when I merge all new commits from `master`

**Comment by k-rus** [comment]
> Is there additional info that's not in #290? Otherwise this info is already going to get merged into `v1.6.1` when I merge all new commits from `master`

No, this PR is not different from what is already in the master.

**Comment by solugebefola** [comment]
OK, then no need for this PR :)

**Pull request closed without merging**
