### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by solugebefola**

### CODE REVIEW

**Comment by RobAtticus** [comment]
If you change it to bash it does some weird highlighting on the output, I think `text` is preferred

**Comment by solugebefola** [comment]
`text` breaks Jenkins.  It's not a known language for highlightjs (at least the version that's in the repo)

**Comment by solugebefola** [comment]
can just leave without language

**Comment by solugebefola** [comment]
Have to test, but this was the fix I had to use to fix the 1.2 branch of docs

**Comment by RobAtticus** [comment]
Okay, change to blank then, bash ends up looking weird.

**Pull request merged**
