### PR TITLE
Remove getting-started/exploring-enterprise

### PR DESCRIPTION
**Pull request by alexthinath**
This section is no longer relevant with our current cloud model. I believe it can be removed altogether to avoid potential confusion.

### CODE REVIEW

**Comment by mfreed** [comment]
I don't think the commit should be removing the markdown (e.g., for on-premise customers), but instead that the commit should just removing the section from page-index.js (and any other links).

**Comment by solugebefola** [comment]
Status update on this PR?

**Comment by alexthinath** [comment]
I didnt make any content changes since I wasnt sure how the team wanted to address removing this section. The smallest change github would let me file an issue was adding a line. I'm fine to follow Mike's suggestion, that seems good.

**Comment by solugebefola** [comment]
So is the plan to just remove the page-index entry?  It will be completely unreachable.  Or is the plan to hide the page except by direct link?  In that case, it requires changing the page-index type to `NON_MENU_PAGE`

**Comment by solugebefola** [comment]
Either way, any other links on the site would need to be removed

**Comment by alexthinath** [comment]
deleting this

**Pull request closed without merging**
